music:
  storage:
    type: local
    uri: http://localhost:5000/file?password=qBw66B6RvanBj5CC64REzmBFu2ruY3b9fDe5XxFtts&path=/Server/

server:
  jwt:
    secret: givfbvw_4OWjXzWsmhAoqj_h8p5tTRnPE0MEqPrDuSoCx1RSZNoBFKT26g15hg4diFR-yALou-OCGgChNgsE7X_kgn_8ViKhMuQtd4O_TSWOAFKH57S81RP5Hwd58jErMPURwKCDKqDMl8NiXa_e3wxFoi17ejm1frj590jL22gk1AhGwpoOpNmZrq0SDtRKN_G2LU33nkG_BI5ooY5BYTuPmWS1u4qDIxRKNDMN_QtmJnPVz9BBNY5I1TfL52acBKtzgvF64kOFnTQyWuEauTj4J9Q5YJjJtRmagCpHxhDlxKdjC9lc0jalwZzUzQwfDA_sx03OEY8Usb4a3KX1AQ
    validity-mins: 60
  upload:
    max-file-size-mb: 150
    max-request-size-mb: 150

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:55432/musicx
    username: admin
    password: admin
    hibernate:
      show_sql: true
      ddl-auto: validate
  hibernate:
      ddl-auto: create-drop

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:music-portal-test
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
